//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZJ.Intern4job.Model.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Intern4jobEntities : DbContext
    {
        public Intern4jobEntities()
            : base("name=Intern4jobEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate> intern4job_candidate { get; set; }
        public virtual DbSet<Employer> intern4job_employer { get; set; }
        public virtual DbSet<Profession> intern4job_profession { get; set; }
        public virtual DbSet<User> intern4job_user { get; set; }
    }
}
